version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbearia-api
    env_file:
      - .env
    environment:
      - PORT=8001
      - NODE_ENV=production
    ports:
      - "8001:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8001/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
